"""
QOFT v5.1 — ANU QRNG Noise Source Connector
============================================
Drop-in replacement for MockQRNGSource in qoft_v51_engine.py.

Pulls true quantum random numbers from:
  Australian National University Quantum Random Number Generator
  https://quantumnumbers.anu.edu.au
  API endpoint: https://api.quantumnumbers.anu.edu.au

Numbers are generated by measuring quantum fluctuations of the optical vacuum.
Guaranteed phase-incoherent relative to any internal system dynamics.

Usage:
  from qrng_source import ANUQRNGSource
  src = ANUQRNGSource(api_key="YOUR_KEY_HERE")
  # then pass src as noise_source to run_simulation_pluggable()

Requires: requests  (pip install requests)
"""

import os
import math
import time
import requests
import numpy as np
from typing import Optional


# ── Constants ────────────────────────────────────────────────────────────────

ANU_API_URL   = "https://api.quantumnumbers.anu.edu.au"
CACHE_SIZE    = 1024          # integers fetched per API call (max 1024)
MAX_RETRIES   = 3
RETRY_DELAY   = 1.5           # seconds between retries
REQUEST_TIMEOUT = 10          # seconds


# ── ANU QRNG Source ──────────────────────────────────────────────────────────

class ANUQRNGSource:
    """
    True quantum random noise source via ANU QRNG API.

    Implements the NoiseSource interface from qoft_v51_engine.py:
        .normal(loc, scale, size) -> np.ndarray

    Internally:
      - Fetches uint16 integers from the ANU API in batches of CACHE_SIZE
      - Converts to float64 uniform [0, 1] via division by 65535
      - Transforms uniform -> Gaussian via Box-Muller transform
      - Caches surplus draws to minimise API calls
      - Logs every draw to ctx noise_log for auditability (canonical contract)

    API key:
      Pass directly OR set env var:  QRNG_API_KEY=your_key
    """

    def __init__(self, api_key: Optional[str] = None, verbose: bool = True):
        self.label = "ANU_QRNG"
        self.draw_count = 0
        self.api_call_count = 0
        self.verbose = verbose

        # Resolve API key
        self.api_key = api_key or os.environ.get("QRNG_API_KEY", "")
        if not self.api_key:
            raise ValueError(
                "ANU QRNG API key required.\n"
                "  Option 1: ANUQRNGSource(api_key='your_key')\n"
                "  Option 2: export QRNG_API_KEY=your_key\n"
                "  Get a key at: https://quantumnumbers.anu.edu.au"
            )

        self._cache: list[float] = []   # uniform floats waiting to be used

        if self.verbose:
            print(f"[ANUQRNGSource] Initialised. Testing connection...")
            self._prefetch()
            print(f"[ANUQRNGSource] Connected. {len(self._cache)} numbers in cache.")


    # ── Internal fetch ────────────────────────────────────────────────────────

    def _fetch_batch(self, n: int = CACHE_SIZE) -> list[float]:
        """
        Fetch n uint16 integers from ANU API, return as uniform floats in [0,1].
        Retries up to MAX_RETRIES on failure.
        """
        n = min(n, 1024)  # API maximum
        params = {"length": n, "type": "uint16"}
        headers = {"x-api-key": self.api_key}

        for attempt in range(1, MAX_RETRIES + 1):
            try:
                resp = requests.get(
                    ANU_API_URL,
                    params=params,
                    headers=headers,
                    timeout=REQUEST_TIMEOUT
                )
                resp.raise_for_status()
                data = resp.json()

                if data.get("success") is False or "data" not in data:
                    raise ValueError(f"API error: {data}")

                raw = data["data"]          # list of uint16 integers
                self.api_call_count += 1
                # Normalise to [0, 1]
                return [x / 65535.0 for x in raw]

            except Exception as e:
                if attempt < MAX_RETRIES:
                    if self.verbose:
                        print(f"[ANUQRNGSource] Retry {attempt}/{MAX_RETRIES}: {e}")
                    time.sleep(RETRY_DELAY)
                else:
                    raise RuntimeError(
                        f"ANU QRNG API failed after {MAX_RETRIES} attempts: {e}"
                    )


    def _prefetch(self):
        """Refill the cache."""
        self._cache.extend(self._fetch_batch(CACHE_SIZE))


    def _get_uniforms(self, n: int) -> np.ndarray:
        """Return n uniform [0,1] floats, refilling cache as needed."""
        while len(self._cache) < n:
            self._prefetch()
        vals = self._cache[:n]
        self._cache = self._cache[n:]
        return np.array(vals, dtype=np.float64)


    # ── Box-Muller transform ─────────────────────────────────────────────────

    @staticmethod
    def _box_muller(u1: np.ndarray, u2: np.ndarray) -> np.ndarray:
        """
        Transform two uniform arrays to standard normal via Box-Muller.
        Returns array of same length as u1.
        Clamps u1 away from 0 to avoid log(0).
        """
        u1 = np.clip(u1, 1e-10, 1.0)
        z = np.sqrt(-2.0 * np.log(u1)) * np.cos(2.0 * math.pi * u2)
        return z


    # ── Public interface (matches NoiseSource contract) ───────────────────────

    def normal(self, loc: float = 0.0, scale: float = 1.0,
               size=None) -> np.ndarray:
        """
        Return quantum-random normal samples with given loc and scale.
        Compatible with np.random.Generator.normal() signature.
        """
        if size is None:
            n = 1
            scalar_out = True
        elif isinstance(size, int):
            n = size
            scalar_out = False
        else:
            n = int(np.prod(size))
            scalar_out = False

        # Need 2n uniforms for Box-Muller (pairs)
        n_fetch = n + (n % 2)          # round up to even
        uniforms = self._get_uniforms(n_fetch * 2)
        u1 = uniforms[:n_fetch]
        u2 = uniforms[n_fetch:n_fetch * 2]

        normals = self._box_muller(u1, u2)[:n]
        result = loc + scale * normals
        self.draw_count += n

        if scalar_out:
            return float(result[0])
        if isinstance(size, (list, tuple)):
            return result.reshape(size)
        return result


    def log_draw(self, ctx: dict):
        """Log this draw to ctx noise_log (canonical auditability contract)."""
        ctx.setdefault("noise_log", []).append({
            "step": ctx.get("step", -1),
            "source": self.label,
            "draw_n": self.draw_count,
            "api_calls": self.api_call_count,
            "cache_remaining": len(self._cache),
        })


    def stats(self) -> dict:
        """Return usage summary."""
        return {
            "source": self.label,
            "total_draws": self.draw_count,
            "api_calls": self.api_call_count,
            "cache_remaining": len(self._cache),
            "numbers_per_api_call": CACHE_SIZE,
        }


# ── Offline fallback (whitened PRNG) ─────────────────────────────────────────

class WhitenedPRNGSource:
    """
    Offline fallback that approximates phase-incoherent noise without an API.

    Uses a PRNG but applies spectral whitening (randomise phase in frequency
    domain) to remove any phase structure that could couple to observer dynamics.
    Not true QRNG — but a better mock than hash-chain re-seeding.

    Use this for:
    - Offline development when ANU API is unavailable
    - CI/testing without network access
    - Validating the engine before spending API quota
    """

    def __init__(self, seed: int = 0):
        self.label = "WhitenedPRNG"
        self.draw_count = 0
        self._rng = np.random.default_rng(seed)

    def normal(self, loc: float = 0.0, scale: float = 1.0,
               size=None) -> np.ndarray:
        if size is None:
            raw = self._rng.normal(loc, scale, size=64)
            # Whiten: randomise phase in freq domain
            fft = np.fft.rfft(raw)
            phases = self._rng.uniform(0, 2 * math.pi, size=len(fft))
            fft_whitened = np.abs(fft) * np.exp(1j * phases)
            whitened = np.fft.irfft(fft_whitened)[:64]
            # Rescale to requested loc/scale
            whitened = loc + scale * (whitened - whitened.mean()) / (whitened.std() + 1e-9)
            self.draw_count += 1
            return float(whitened[0])

        n = size if isinstance(size, int) else int(np.prod(size))
        # Pad to next power of 2 for clean FFT
        n_pad = max(n, 64)
        raw = self._rng.normal(0, 1, size=n_pad)
        fft = np.fft.rfft(raw)
        phases = self._rng.uniform(0, 2 * math.pi, size=len(fft))
        fft_whitened = np.abs(fft) * np.exp(1j * phases)
        whitened = np.fft.irfft(fft_whitened)[:n]
        result = loc + scale * (whitened - whitened.mean()) / (whitened.std() + 1e-9)
        self.draw_count += n
        if isinstance(size, (list, tuple)):
            return result.reshape(size)
        return result

    def log_draw(self, ctx: dict):
        ctx.setdefault("noise_log", []).append({
            "step": ctx.get("step", -1),
            "source": self.label,
            "draw_n": self.draw_count,
        })

    def stats(self) -> dict:
        return {"source": self.label, "total_draws": self.draw_count}


# ── Quick test ────────────────────────────────────────────────────────────────

def test_source(src, n: int = 1000):
    """
    Basic statistical sanity check on any NoiseSource.
    Draws n samples, checks mean ≈ 0, std ≈ 1.
    """
    ctx = {"step": 0}
    samples = src.normal(loc=0.0, scale=1.0, size=n)
    src.log_draw(ctx)
    mean = float(np.mean(samples))
    std = float(np.std(samples))
    print(f"[{src.label}] n={n} | mean={mean:.4f} (want ~0) | std={std:.4f} (want ~1)")
    assert abs(mean) < 0.15, f"Mean too far from 0: {mean}"
    assert 0.85 < std < 1.15, f"Std too far from 1: {std}"
    print(f"[{src.label}] Sanity check passed.")
    return {"mean": mean, "std": std}


if __name__ == "__main__":
    import sys

    print("=" * 55)
    print("QOFT v5.1 — QRNG Source Connector Test")
    print("=" * 55)

    # Test whitened PRNG (no API key needed)
    print("\n[1] Whitened PRNG (offline fallback)")
    w = WhitenedPRNGSource(seed=42)
    test_source(w, n=500)
    print(f"    Stats: {w.stats()}")

    # Test ANU API if key provided
    api_key = os.environ.get("QRNG_API_KEY") or (sys.argv[1] if len(sys.argv) > 1 else None)
    if api_key:
        print(f"\n[2] ANU QRNG (live API)")
        src = ANUQRNGSource(api_key=api_key)
        test_source(src, n=200)
        print(f"    Stats: {src.stats()}")
    else:
        print("\n[2] ANU QRNG — skipped (no API key)")
        print("    To test: python qrng_source.py YOUR_API_KEY")
        print("    Or:      export QRNG_API_KEY=your_key && python qrng_source.py")
        print("    Get key: https://quantumnumbers.anu.edu.au")
